# Generated by Django 4.1.10 on 2023-09-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
