# Generated by Django 4.1.10 on 2023-09-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_blogdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='description',
            field=models.CharField(max_length=5000000000),
        ),
    ]
